R = 'Rscript'
ref = '../ref/data_maf0.01_rs_snps'

# Gather data files

import glob, os.path
from pathlib import Path   

def find_files(DIR, gwas_dict):
	gwas_path = Path(DIR).glob('GUGC*')
	for f in gwas_path:
		gwas_name = f.name.replace('.gz', '')
		gwas_dict[gwas_name] = str(f)
	return gwas_dict
gwas_dict = {}
gwas_dict = find_files('/projects/MRC-IEU/research/data/evidencehub/summary/gwas/dev/release_candidate/data/results/mrbase/cleaned_for_elastic', gwas_dict)
gwas_dict = find_files('/projects/MRC-IEU/research/data/evidencehub/summary/gwas/dev/release_candidate/data/results/ukbb_broad/cleaned_597_files', gwas_dict)
gwas_dict = find_files('/projects/MRC-IEU/research/data/ukbiobank/summary/gwas/dev/release_candidate/data/ukb-pipeline/cleaned', gwas_dict)


# Create YAML files

rule clump_yaml:
    input:
        lambda wildcards: gwas_dict[wildcards.gwas_name]
    output:
        'data/{gwas_name}.yaml'
    shell:
        "./clump_py --bfile {ref} --gwas {input} --out {output} --snp-col 1 --pval-col --delimiter $'\t' --gzipped 1 --header 0"

